wx:
  miniapp:
    appid: ${WX_APPID}
    secret: ${WX_SECRET}

server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db.bvhwswzakoowoaexqciq.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: ${DB_PASSWORD:fqcqsqcj22}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    time-zone: Asia/Shanghai

# 生产环境日志配置
logging:
  level:
    com.petcare: INFO
    org.springframework: WARN
  file:
    name: /app/logs/application.log

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/**/*.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.petcare